
import type { Metadata } from "next";
import { Bitcount_Prop_Double, Kumar_One, Playwrite_DK_Uloopet_Guides, Pompiere } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Toaster } from "sonner";

import Navbar from "@/components/Navbar";

const nothing = Bitcount_Prop_Double({
  variable: "--font-bitcount-prop-double",
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"],
  adjustFontFallback: false,
});

const english = Playwrite_DK_Uloopet_Guides({
  variable: "--font-playwrite-dk-uloopet-guides-regular",
  weight:"400",
  adjustFontFallback: false,
});

const pompiere = Pompiere({
  variable: "--font-pompiere",
  subsets: ["latin"],
  weight: ["400"]
});

const classy = Kumar_One({
  variable: "--font-classy",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${nothing.variable} ${english.variable} ${pompiere.variable} ${classy.variable} antialiased`}
      >
        <ClerkProvider>
          <Navbar/>
          {children}
        </ClerkProvider>
        <Toaster/>
      </body>
    </html>
  );
}
